import { Router } from "express";
import { requireAuth, requireRole } from "../../middlewares/auth";
import { requireActiveMember } from "../../middlewares/member-access";
import { memberController } from "./member.controller";
import { memberProgressController } from "./member-progress.controller";
import { onboardingController } from "../onboarding/onboarding.controller";
import { sessionRecapController } from "../session-recaps/session-recap.controller";
import { memberBookingController } from "./member-booking.controller";

export const memberRoutes = Router();

memberRoutes.use(requireAuth);
memberRoutes.get("/dashboard", requireRole("MEMBER"), requireActiveMember, memberController.dashboard);
memberRoutes.get("/progress", requireRole("MEMBER"), requireActiveMember, memberProgressController.memberProgress);
memberRoutes.get("/recap.pdf", requireRole("MEMBER"), requireActiveMember, memberProgressController.recapMember);
memberRoutes.get("/recaps", requireRole("MEMBER"), requireActiveMember, sessionRecapController.memberList);
memberRoutes.post("/recaps", requireRole("MEMBER"), requireActiveMember, sessionRecapController.memberCreate);
memberRoutes.patch("/recaps/:recapId", requireRole("MEMBER"), requireActiveMember, sessionRecapController.memberUpdate);
memberRoutes.delete("/recaps/:recapId", requireRole("MEMBER"), requireActiveMember, sessionRecapController.memberRemove);
memberRoutes.get("/onboarding", requireRole("MEMBER"), requireActiveMember, onboardingController.memberList);
memberRoutes.patch("/onboarding/:stepId", requireRole("MEMBER"), requireActiveMember, onboardingController.memberUpdate);
memberRoutes.get("/bookings", requireRole("MEMBER"), requireActiveMember, memberBookingController.list);
memberRoutes.get("/packs", requireRole("MEMBER"), requireActiveMember, memberController.packs);
memberRoutes.get("/settings/profile", requireRole("MEMBER"), requireActiveMember, memberController.getOwnProfile);
memberRoutes.patch("/settings/profile", requireRole("MEMBER"), requireActiveMember, memberController.updateOwnProfile);
memberRoutes.get("/all", requireRole("COACH"), memberController.listMembers);
memberRoutes.post("/", requireRole("COACH"), memberController.create);
memberRoutes.get("/onboarding/templates", requireRole("COACH"), onboardingController.templateList);
memberRoutes.post("/onboarding/templates", requireRole("COACH"), onboardingController.templateCreate);
memberRoutes.patch("/onboarding/templates/:templateId", requireRole("COACH"), onboardingController.templateUpdate);
memberRoutes.delete("/onboarding/templates/:templateId", requireRole("COACH"), onboardingController.templateDelete);
memberRoutes.get("/alerts/onboarding", requireRole("COACH"), onboardingController.alerts);
memberRoutes.get("/:id/progress", requireRole("COACH"), memberProgressController.coachProgress);
memberRoutes.get("/:id/onboarding", requireRole("COACH"), onboardingController.coachList);
memberRoutes.post("/:id/onboarding", requireRole("COACH"), onboardingController.coachCreate);
memberRoutes.patch("/:id/onboarding/:stepId", requireRole("COACH"), onboardingController.coachUpdate);
memberRoutes.delete("/:id/onboarding/:stepId", requireRole("COACH"), onboardingController.coachDelete);
memberRoutes.post("/:id/onboarding/apply/:templateId", requireRole("COACH"), onboardingController.applyTemplate);
memberRoutes.get("/:id/recaps", requireRole("COACH"), sessionRecapController.coachList);
memberRoutes.post("/:id/recaps", requireRole("COACH"), sessionRecapController.create);
memberRoutes.patch("/:id/recaps/:recapId", requireRole("COACH"), sessionRecapController.update);
memberRoutes.delete("/:id/recaps/:recapId", requireRole("COACH"), sessionRecapController.remove);
memberRoutes.patch("/:id/coach-notes", requireRole("COACH"), memberController.updateCoachNotes);
memberRoutes.post("/:id/goals", requireRole("COACH"), memberProgressController.createGoal);
memberRoutes.patch("/:id/goals/:goalId", requireRole("COACH"), memberProgressController.updateGoal);
memberRoutes.delete("/:id/goals/:goalId", requireRole("COACH"), memberProgressController.deleteGoal);
memberRoutes.post("/:id/checkins", requireRole("COACH"), memberProgressController.createCheckIn);
memberRoutes.delete("/:id/checkins/:checkInId", requireRole("COACH"), memberProgressController.deleteCheckIn);
memberRoutes.post("/:id/video-notes", requireRole("COACH"), memberProgressController.createVideoNote);
memberRoutes.delete("/:id/video-notes/:videoNoteId", requireRole("COACH"), memberProgressController.deleteVideoNote);
memberRoutes.get("/:id/recap.pdf", requireRole("COACH"), memberProgressController.recapCoach);
memberRoutes.get("/:id", requireRole("COACH"), memberController.detail);
